notifications:
  webhooks:
    urls:
      - https://kaltura.webhook.office.com/webhookb2/b992a7e1-5ff6-49a7-8d78-2f5e2909a982@0c503748-de3f-4e25-97e2-6819d53a42b6/TravisCI/8ee374eb79a8409fb0ca7cd27a49cf69/4779c8dc-fa74-44a9-9710-010265f09a25
    on_success: never
    on_cancel: never

conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - 17
env:
  global:
    - NODE_OPTIONS="--openssl-legacy-provider"

addons:
  chrome: stable

services:
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - chmod +x ./scripts/travis.sh

script: ./scripts/travis.sh

stages:
  - Tests
  - Release canary
  - Release

jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: Release
      name: 'Releasing a new version'
      if: tag IS present
      env: TRAVIS_MODE=release
      deploy:
        - provider: releases
          api_key: $GH_TOKEN
          file_glob: true
          file: dist/*
          prerelease: false
          skip_cleanup: true
          on:
            branch: master
            tags: true
        - provider: npm
          edge: true
          api_key: $NPM_TOKEN
          email: $NPM_EMAIL
          skip_cleanup: true
          on:
            tags: true
            branch: master
    # publish canary package if on master
    - stage: Release canary
      if: (branch = master) AND (type != pull_request) AND commit_message !~ /^chore\(release\)/
      env: TRAVIS_MODE=releaseCanary
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        email: $NPM_EMAIL
        skip_cleanup: true
        tag: canary
        on:
          tags: false
          branch: master
    # Required tests
    - stage: Tests
      if: ((branch = master) OR (tag IS present) OR (type = pull_request)) AND commit_message !~ /^chore\(release\)/
      name: 'Running lint'
      env: TRAVIS_MODE=lint
    - stage: Tests
      if: ((branch = master) OR (tag IS present) OR (type = pull_request)) AND commit_message !~ /^chore\(release\)/
      name: 'Running Flow type check'
      env: TRAVIS_MODE=flow
    - stage: Tests
      if: ((branch = master) OR (tag IS present) OR (type = pull_request)) AND commit_message !~ /^chore\(release\)/
      name: 'Running unit tests'
      env: TRAVIS_MODE=unitTests
