name: Create patch version

on:
  workflow_dispatch:

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Publish to NPM
        run: |
          npm set registry "https://registry.npmjs.org"
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
          npm version patch
          npm publish --tag patch
          rm -rf .npmrc
        env:
           NPM_AUTH_TOKEN: ${{ secrets.PLAYER_NPM_TOKEN }}
           NPM_TOKEN: ${{ secrets.PLAYER_NPM_TOKEN }}
           NODE_AUTH_TOKEN: ${{ secrets.PLAYER_NPM_TOKEN }}

