name: Create patch version

on:
  workflow_dispatch:

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Update NPM Tag
        env:
          PLAYER_CENTRAL_ACCOUNT_ID: ${{ secrets.PLAYER_CENTRAL_ACCOUNT_ID }}
          PLAYER_SERVICES_ACCOUNT_ID: ${{ secrets.PLAYER_SERVICES_ACCOUNT_ID }}
          PLAYER_S3_BUCKET_DEPLOYMENT: ${{ secrets.PLAYER_S3_BUCKET_DEPLOYMENT }}
          PLAYER_S3_BUCKET_APPS: ${{ secrets.PLAYER_S3_BUCKET_APPS }}
          PLAYER_NPM_TOKEN: ${{ secrets.PLAYER_NPM_TOKEN }}
          PLAYER_LAMBDA_NAME: ${{ secrets.PLAYER_LAMBDA_NAME }}
          PLAYER_MSTEAMS_WEBHOOK: ${{ secrets.PLAYER_MSTEAMS_WEBHOOK }}
          PLAYER_GITHUB_BOT_TOKEN: ${{ secrets.PLAYER_GITHUB_BOT_TOKEN }}
        run: |
          npm dist-tag add @playkit-js/playkit-js@0.84.2-canary.0-2fe7e02 patch

